import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ApiRequestError, apiRequest } from "../api/client";
import type { PriceBreakdown, Product } from "../types";
import { useB2BSessionGuard } from "../hooks/useB2BSessionGuard";
import { responsiveImage } from "../utils/image";
const money = (value?: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
const diamondWeight = (product: Product) => (product.diamonds || []).reduce((sum, diamond) => sum + Number(diamond.caratWeight || 0), 0);
function B2BPrice({ product, price }: { product: Product; price: PriceBreakdown & { display?: { showMaking?: boolean; showCertificate?: boolean; showGst?: boolean } } }) { const display = price.display; return <article className="rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-5 space-y-3"><h2 className="font-primary text-xl text-[var(--color-teal)]">{price.karat?.toUpperCase()} trade price</h2><p className="flex justify-between text-sm"><span>Gold weight</span><b>{price.grossWeight} g</b></p><p className="flex justify-between text-sm"><span>Diamond weight</span><b>{diamondWeight(product)} ct</b></p>{display?.showMaking !== false && <p className="flex justify-between text-sm"><span>Making charge</span><b>{money(price.makingCharge)}</b></p>}{display?.showCertificate !== false && <p className="flex justify-between text-sm"><span>Certificate charge</span><b>{money(price.certificateCharges)}</b></p>}{display?.showGst !== false && <p className="flex justify-between text-sm"><span>GST</span><b>{money(price.gst)}</b></p>}<p className="flex justify-between border-t border-[var(--color-border)] pt-3 font-semibold text-[var(--color-teal)]"><span>Final total</span><b>{money(price.finalPrice)}</b></p></article>; }
export default function B2BProductDetails() {
  useB2BSessionGuard();
  const { identifier = "" } = useParams(); const navigate = useNavigate(); const [product, setProduct] = useState<Product | null>(null); const [error, setError] = useState("");
  useEffect(() => { apiRequest<Product>("/b2b/products/" + encodeURIComponent(identifier)).then(setProduct).catch(reason => { if (reason instanceof ApiRequestError && reason.statusCode === 401) navigate("/b2b/access", { replace: true }); else setError(reason instanceof Error ? reason.message : "Unable to load product"); }); }, [identifier, navigate]);
  if (error) return <main className="p-10 text-[var(--color-error)]">{error}</main>; if (!product) return <main className="p-10 text-[var(--color-text-muted)]">Loading B2B product…</main>;
  return <main className="min-h-screen bg-[var(--color-bg)] px-5 py-10 md:px-12"><Link to="/b2b/catalog" className="text-sm text-[var(--color-teal)]">← Back to catalogue</Link><section className="mx-auto mt-6 grid max-w-7xl gap-10 md:grid-cols-2"><img src={responsiveImage(product.images?.[0]?.url, 1200)} alt={product.title} className="w-full rounded-[var(--radius-lg)] object-cover" /><div className="space-y-6"><div><p className="section-label">B2B Gold</p><h1 className="font-primary text-4xl text-[var(--color-teal)]">{product.title}</h1><p className="mt-3 text-sm text-[var(--color-text-muted)]">{product.description}</p></div><div className="grid gap-4">{(product.prices || []).map(price => <B2BPrice key={price.karat} product={product} price={price as PriceBreakdown & { display?: { showMaking?: boolean; showCertificate?: boolean; showGst?: boolean } }} />)}</div></div></section></main>;
}