import { FormEvent, useEffect, useState } from "react";
import { Navigate, NavLink, Route, Routes, useNavigate } from "react-router-dom";
import { adminApi, type AdminUser, type BannerPayload, type Coupon, type ManagedUser } from "../api/admin.api";
import type { Banner } from "../api/banner.api";
import type { Announcement } from "../api/announcement.api";
import { ApiRequestError } from "../api/client";

const errorMessage = (error: unknown) => error instanceof ApiRequestError ? error.message : "Request failed. Please try again.";
const emptyCoupon = { code: "", discountType: "percentage" as const, discountValue: 0, minimumCartValue: 0, expiryDate: "", usageLimit: null as number | null, activeStatus: true };

function Login({ onLogin }: { onLogin: (admin: AdminUser) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (e: FormEvent) => { e.preventDefault(); setLoading(true); setError(""); try { onLogin(await adminApi.login(email, password)); } catch (err) { setError(errorMessage(err)); } finally { setLoading(false); } };
  return <main className="min-h-screen grid place-items-center bg-[var(--color-bg)] p-5"><form onSubmit={submit} className="w-full max-w-sm border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-7 space-y-4"><p className="section-label">TBA administration</p><h1 className="font-primary text-3xl text-[var(--color-teal)]">Admin sign in</h1>{error && <p className="text-sm text-red-700">{error}</p>}<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email" className="admin-input"/><input required type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" className="admin-input"/><button disabled={loading} className="admin-button w-full">{loading ? "Signing in…" : "Sign in"}</button></form></main>;
}

function Layout({ admin, onLogout }: { admin: AdminUser; onLogout: () => void }) { return <div className="min-h-screen bg-[var(--color-bg)] text-[var(--color-text)]"><header className="border-b border-[var(--color-border)] px-5 py-4 flex flex-wrap gap-4 justify-between items-center"><div><span className="section-label">TBA</span><b className="font-primary ml-2">Admin</b></div><span className="text-xs">{admin.name} · {admin.role} <button onClick={onLogout} className="ml-3 underline">Log out</button></span></header><div className="md:flex"><nav className="md:w-52 border-b md:border-b-0 md:border-r border-[var(--color-border)] p-3 flex md:flex-col gap-1"><NavLink end to="/admin" className="admin-nav">Dashboard</NavLink><NavLink to="/admin/banners" className="admin-nav">Banners</NavLink><NavLink to="/admin/announcements" className="admin-nav">Announcements</NavLink><NavLink to="/admin/coupons" className="admin-nav">Coupons</NavLink>{admin.role === "superadmin" && <NavLink to="/admin/users" className="admin-nav">Users</NavLink>}</nav><main className="flex-1 p-5 md:p-8"><Routes><Route index element={<Dashboard/>}/><Route path="banners" element={<Banners/>}/><Route path="announcements" element={<Announcements/>}/><Route path="coupons" element={<Coupons/>}/><Route path="users" element={admin.role === "superadmin" ? <Users/> : <Navigate to="/admin" replace/>}/><Route path="*" element={<Navigate to="/admin" replace/>}/></Routes></main></div></div>; }
function Dashboard() { return <section><p className="section-label">Overview</p><h1 className="font-primary text-3xl text-[var(--color-teal)]">Content & customer controls</h1><p className="mt-3 text-sm text-[var(--color-text-muted)]">Use the navigation to maintain homepage banners, announcements, promotional coupons, and customer access.</p></section>; }
function Banners() { const [items,setItems]=useState<Banner[]>([]); const [editing,setEditing]=useState<Banner|null>(null); const [message,setMessage]=useState(""); const load=()=>adminApi.banners().then(setItems).catch(e=>setMessage(errorMessage(e))); useEffect(()=>{void load();},[]); const save=async(p:BannerPayload)=>{try { editing?await adminApi.updateBanner(editing._id,p):await adminApi.createBanner(p);setEditing(null);void load();}catch(e){setMessage(errorMessage(e));}}; const shift=async(b:Banner,delta:number)=>{await adminApi.updateBanner(b._id,{order:b.order+delta});void load();}; return <section className="space-y-5"><Title title="Banners" message={message}/><BannerForm value={editing} onCancel={()=>setEditing(null)} onSave={save}/><div className="space-y-2">{items.length===0?<Empty/>:items.map(b=><div className="admin-row" key={b._id}><img src={b.image} className="w-20 h-12 object-cover"/><span className="flex-1">{b.title||"Untitled"} <small>order {b.order}</small></span><button onClick={()=>shift(b,-1)}>↑</button><button onClick={()=>shift(b,1)}>↓</button><button onClick={()=>adminApi.setBannerActive(b._id,!b.isActive).then(load)}>{b.isActive?"Disable":"Enable"}</button><button onClick={()=>setEditing(b)}>Edit</button><button className="text-red-700" onClick={()=>confirm("Delete this banner?")&&adminApi.deleteBanner(b._id).then(load)}>Delete</button></div>)}</div></section>; }
function BannerForm({value,onSave,onCancel}:{value:Banner|null;onSave:(p:BannerPayload)=>void;onCancel:()=>void}) { const [p,setP]=useState<BannerPayload>({title:"",link:"",order:0,image:""}); useEffect(()=>setP(value?{title:value.title,link:value.link,order:value.order,image:value.image,mobileImage:value.mobileImage||""}:{title:"",link:"",order:0,image:""}),[value]); return <form onSubmit={e=>{e.preventDefault();onSave(p)}} className="admin-form"><b>{value?"Edit banner":"New banner"}</b><input className="admin-input" placeholder="Title" value={p.title} onChange={e=>setP({...p,title:e.target.value})}/><input className="admin-input" placeholder="Image URL (or upload below)" value={p.image} onChange={e=>setP({...p,image:e.target.value})}/><input className="admin-input" type="file" accept="image/*" onChange={e=>setP({...p,file:e.target.files?.[0]})}/><input className="admin-input" placeholder="Mobile image URL" value={p.mobileImage} onChange={e=>setP({...p,mobileImage:e.target.value})}/><input className="admin-input" placeholder="Link" value={p.link} onChange={e=>setP({...p,link:e.target.value})}/><input className="admin-input" type="number" placeholder="Order" value={p.order} onChange={e=>setP({...p,order:Number(e.target.value)})}/><button className="admin-button">Save banner</button>{value&&<button type="button" onClick={onCancel}>Cancel</button>}</form>; }
function Announcements() { const [items,setItems]=useState<Announcement[]>([]); const [edit,setEdit]=useState<Announcement|null>(null); const [message,setMessage]=useState(""); const load=()=>adminApi.announcements().then(setItems).catch(e=>setMessage(errorMessage(e))); useEffect(()=>{void load();},[]); const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const p={message:String(f.get("message")),order:Number(f.get("order"))};try{edit?await adminApi.updateAnnouncement(edit._id,p):await adminApi.createAnnouncement(p);setEdit(null);void load()}catch(err){setMessage(errorMessage(err))}};return <section className="space-y-5"><Title title="Announcements" message={message}/><form key={edit?edit._id:"new"} onSubmit={save} className="admin-form"><b>{edit?"Edit announcement":"New announcement"}</b><input required name="message" defaultValue={edit?.message} className="admin-input" placeholder="Message"/><input required name="order" type="number" defaultValue={edit?.order??0} className="admin-input"/><button className="admin-button">Save</button>{edit&&<button type="button" onClick={()=>setEdit(null)}>Cancel</button>}</form>{items.length===0?<Empty/>:items.map(a=><div className="admin-row" key={a._id}><span className="flex-1">{a.message} <small>order {a.order}</small></span><button onClick={()=>adminApi.setAnnouncementActive(a._id,!a.isActive).then(load)}>{a.isActive?"Disable":"Enable"}</button><button onClick={()=>setEdit(a)}>Edit</button><button className="text-red-700" onClick={()=>confirm("Delete this announcement?")&&adminApi.deleteAnnouncement(a._id).then(load)}>Delete</button></div>)}</section>; }
function Coupons() { const [items,setItems]=useState<Coupon[]>([]);const [edit,setEdit]=useState<Coupon|null>(null);const [message,setMessage]=useState("");const load=()=>adminApi.coupons().then(setItems).catch(e=>setMessage(errorMessage(e)));useEffect(()=>{void load();},[]);const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const p={code:String(f.get("code")).toUpperCase(),discountType:String(f.get("discountType")) as Coupon["discountType"],discountValue:Number(f.get("discountValue")),minimumCartValue:Number(f.get("minimumCartValue")),expiryDate:String(f.get("expiryDate")),usageLimit:f.get("usageLimit")?Number(f.get("usageLimit")):null,activeStatus:f.get("activeStatus")==="on"};try{edit?await adminApi.updateCoupon(edit._id,p):await adminApi.createCoupon(p);setEdit(null);void load()}catch(err){setMessage(errorMessage(err))}};return <section className="space-y-5"><Title title="Coupons" message={message}/><form key={edit?edit._id:"new"} onSubmit={save} className="admin-form"><b>{edit?"Edit coupon":"New coupon"}</b><input required name="code" defaultValue={edit?.code} className="admin-input" placeholder="Code"/><select name="discountType" defaultValue={edit?.discountType||"percentage"} className="admin-input"><option value="percentage">Percentage</option><option value="flat">Flat amount</option></select><input required name="discountValue" type="number" min="0" defaultValue={edit?.discountValue} className="admin-input" placeholder="Discount value"/><input required name="minimumCartValue" type="number" min="0" defaultValue={edit?.minimumCartValue??0} className="admin-input" placeholder="Minimum cart value"/><input required name="expiryDate" type="datetime-local" defaultValue={edit?.expiryDate?.slice(0,16)} className="admin-input"/><input name="usageLimit" type="number" min="1" defaultValue={edit?.usageLimit??""} className="admin-input" placeholder="Usage limit (optional)"/><label><input name="activeStatus" type="checkbox" defaultChecked={edit?.activeStatus??true}/> Active</label><button className="admin-button">Save coupon</button>{edit&&<button type="button" onClick={()=>setEdit(null)}>Cancel</button>}</form>{items.length===0?<Empty/>:items.map(c=><div className="admin-row" key={c._id}><span className="flex-1"><b>{c.code}</b> · {c.discountType === "percentage" ? `${c.discountValue}%` : `₹${c.discountValue}`} <small>{c.activeStatus?"active":"inactive"}, used {c.usedCount}{c.usageLimit!==null?`/${c.usageLimit}`:""}</small></span><button onClick={()=>setEdit(c)}>Edit</button><button className="text-red-700" onClick={()=>confirm("Delete this coupon?")&&adminApi.deleteCoupon(c._id).then(load)}>Delete</button></div>)}</section>; }
function Users() {const [items,setItems]=useState<ManagedUser[]>([]);const [message,setMessage]=useState("");const load=()=>adminApi.users().then(setItems).catch(e=>setMessage(errorMessage(e)));useEffect(()=>{void load();},[]);return <section className="space-y-5"><Title title="Customers" message={message}/>{items.length===0?<Empty/>:items.map(u=><div className="admin-row" key={u._id}><span className="flex-1"><b>{u.name}</b> · {u.email} <small>{u.phone||"No phone"}</small></span><button onClick={()=>adminApi.setUserBlocked(u._id,!u.isBlocked).then(load)} className={u.isBlocked?"text-emerald-700":"text-red-700"}>{u.isBlocked?"Unblock":"Block"}</button></div>)}</section>;}
function Title({title,message}:{title:string;message:string}){return <><p className="section-label">Management</p><h1 className="font-primary text-3xl text-[var(--color-teal)]">{title}</h1>{message&&<p className="text-sm text-red-700">{message}</p>}</>}; function Empty(){return <p className="text-sm text-[var(--color-text-muted)]">Nothing to show yet.</p>}
export default function AdminApp(){const [admin,setAdmin]=useState<AdminUser|null>(null);const [ready,setReady]=useState(false);const nav=useNavigate();useEffect(()=>{adminApi.me().then(setAdmin).catch(()=>adminApi.refresh().then(setAdmin).catch(()=>null)).finally(()=>setReady(true))},[]);const logout=async()=>{await adminApi.logout().catch(()=>null);setAdmin(null);nav("/admin/login")};if(!ready)return <main className="min-h-screen grid place-items-center">Loading administration…</main>;return <Routes><Route path="login" element={admin?<Navigate to="/admin" replace/>:<Login onLogin={a=>{setAdmin(a);nav("/admin")}}/>}/><Route path="*" element={admin?<Layout admin={admin} onLogout={logout}/>:<Navigate to="/admin/login" replace/>}/></Routes>}
