import { ChangeEvent, DragEvent, FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { adminApi, type DiamondCategory, type PricingConfig } from "../api/admin.api";
import { useToast } from "../context/ToastContext";
import type { Category, DiamondEntry, MoissaniteEntry, PriceBreakdown, Product } from "../types";
import { PRODUCT_COLORS } from "../constants/product";

type Karat = "14kt" | "18kt";
type Image = { url: string; source: "link" | "upload" };
type FormField = "title" | "SKU" | "metal" | "pricingConfigKey" | "mainCategory" | "subCategory" | "images";
type FormErrors = Partial<Record<FormField, string>>;
type ProductForm = {
  SKU: string; title: string; description: string; metal: "" | "gold" | "silver"; pricingConfigKey: string;
  mainCategory: string; subCategory: string; images: Image[]; videoLink: string; sizes: number[]; colors: string[];
  grossWeight: number; netWeight: number; moissaniteCaratWeight: number; moissaniteEntries: MoissaniteEntry[];
  diamonds: DiamondEntry[]; isBestSeller: boolean; isNewProduct: boolean; isActive: boolean;
};
const STANDARD_RING_SIZES = Array.from({ length: 21 }, (_, index) => index + 5);
const blank = (): ProductForm => ({ SKU: "", title: "", description: "", metal: "", pricingConfigKey: "", mainCategory: "", subCategory: "", images: [], videoLink: "", sizes: STANDARD_RING_SIZES, colors: [], grossWeight: 0, netWeight: 0, moissaniteCaratWeight: 0, moissaniteEntries: [], diamonds: [], isBestSeller: false, isNewProduct: false, isActive: true });
const categoryId = (value?: string | { _id: string } | null) => typeof value === "string" ? value : value?._id || "";
const categoryName = (value?: Category | string | null) => !value ? "Uncategorised" : typeof value === "string" ? value : value.name;
const currency = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
const number = (value: string) => value === "" ? 0 : Number(value);

function Field({ name, label, hint, error, required, children }: { name?: string; label: string; hint?: string; error?: string; required?: boolean; children: React.ReactNode }) { return <label className={`admin-field ${error ? "admin-field--error" : ""}`}><span>{label} {required && <em>*</em>}</span>{children}{error ? <small id={`${name}-error`} role="alert">{error}</small> : hint && <small>{hint}</small>}</label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="admin-toggle-card"><span><b>{label}</b></span><input aria-label={label} type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><i /></label>; }
function MediaCard({ index, image, uploading, onUpload, onUrl, onRemove }: { index: number; image?: Image; uploading: boolean; onUpload: (file: File) => void; onUrl: (url: string) => void; onRemove: () => void }) {
  const fileChange = (e: ChangeEvent<HTMLInputElement>) => e.target.files?.[0] && onUpload(e.target.files[0]);
  const drop = (e: DragEvent<HTMLLabelElement>) => { e.preventDefault(); const file = e.dataTransfer.files[0]; if (file) onUpload(file); };
  return <article className="admin-media-card"><div className="admin-media-preview">{image ? <img src={image.url} alt={`Product image ${index + 1}`} /> : <span>Image {index + 1}{index === 0 ? "  - Primary" : ""}</span>}</div><div className="admin-media-body"><b>Image {index + 1}{index === 0 ? " (Primary)" : ""}</b><label className="admin-dropzone" onDragOver={(e) => e.preventDefault()} onDrop={drop}><input type="file" accept="image/*" onChange={fileChange} />{uploading ? "Uploading image..." : "Upload or drop an image"}</label><div className="admin-media-or">or paste an external URL</div><input className="admin-input" value={image?.source === "link" ? image.url : ""} onChange={(e) => onUrl(e.target.value)} placeholder="https://" />{image && <button type="button" className="admin-text-button danger" onClick={onRemove}>Remove</button>}</div></article>;
}

export default function Products() {
  const { showToast } = useToast();
  const [items, setItems] = useState<Product[]>([]), [categories, setCategories] = useState<Category[]>([]), [configs, setConfigs] = useState<PricingConfig[]>([]), [diamondCategories, setDiamondCategories] = useState<DiamondCategory[]>([]);
  const [form, setForm] = useState<ProductForm>(blank()), [editing, setEditing] = useState<Product | null>(null), [preview, setPreview] = useState<PriceBreakdown[]>([]);
  const [creating, setCreating] = useState(false), [saving, setSaving] = useState(false), [uploading, setUploading] = useState<number | null>(null), [errors, setErrors] = useState<FormErrors>({}), [submitted, setSubmitted] = useState(false), [newDiamondCategory, setNewDiamondCategory] = useState(""), [newDiamondSubType, setNewDiamondSubType] = useState("");
  const firstInvalidRef = useRef<HTMLElement | null>(null);
  const load = useCallback(async () => { const [products, categoryList, configList, diamondCategoryList] = await Promise.all([adminApi.adminProducts(), adminApi.categories(), adminApi.pricingConfigs(), adminApi.diamondCategories()]); setItems(products); setCategories(categoryList); setConfigs(configList); setDiamondCategories(diamondCategoryList); }, []);
  useEffect(() => { void load().catch(() => showToast("Could not load catalogue data.", "error")); }, [load, showToast]);
  const goldRoot = useMemo(() => categories.find((c) => c.metal === "gold" && c.categoryKind === "metal-root"), [categories]);
  const goldLeaves = useMemo(() => categories.filter((c) => c.metal === "gold" && c.categoryKind === "subcategory" && categoryId(c.parent) === goldRoot?._id), [categories, goldRoot]);
  const silverTypes = useMemo(() => categories.filter((c) => c.metal === "silver" && c.categoryKind === "type"), [categories]);
  const silverLeaves = useMemo(() => categories.filter((c) => c.metal === "silver" && c.categoryKind === "subcategory" && categoryId(c.parent) === form.mainCategory), [categories, form.mainCategory]);
  const selectedSilverType = silverTypes.find((category) => category._id === form.mainCategory)?.name.toLowerCase();
  const compatibleConfigs = useMemo(() => configs.filter((config) => config.metal === form.metal && (form.metal !== "silver" || Boolean(selectedSilverType) && config.categoryType.toLowerCase() === selectedSilverType)), [configs, form.metal, selectedSilverType]);
  // The hidden Gold root is required by the API. Reconcile after category data arrives,
  // not only at the instant the metal selector changes.
  useEffect(() => {
    if (form.metal === "gold" && !form.mainCategory && goldRoot?._id) {
      setForm((current) => current.metal === "gold" && !current.mainCategory ? { ...current, mainCategory: goldRoot._id } : current);
    }
  }, [form.metal, form.mainCategory, goldRoot]);
  const validateProductForm = useCallback((state: ProductForm): FormErrors => {
    const next: FormErrors = {};
    if (!state.title.trim()) next.title = "Product title is required.";
    if (!state.SKU.trim()) next.SKU = "SKU is required.";
    if (!state.metal) next.metal = "Select a metal.";
    if (!state.pricingConfigKey) next.pricingConfigKey = "Select a pricing configuration.";
    if (!state.mainCategory) next.mainCategory = state.metal === "silver" ? "Select a Silver type." : "Select a product category.";
    if (!state.subCategory) next.subCategory = state.metal === "gold" ? "Select a Gold subcategory." : "Select a Silver subcategory.";
    if (!state.images.length) next.images = "Add at least one product image.";
    return next;
  }, []);
  useEffect(() => { if (submitted) setErrors(validateProductForm(form)); }, [form, submitted, validateProductForm]);
  useEffect(() => { if (!firstInvalidRef.current) return; firstInvalidRef.current.scrollIntoView({ behavior: "smooth", block: "center" }); firstInvalidRef.current.focus({ preventScroll: true }); firstInvalidRef.current = null; }, [errors]);
  const fieldProps = (field: FormField) => ({ "data-field": field, "aria-invalid": Boolean(errors[field]), "aria-describedby": errors[field] ? `${field}-error` : undefined, onBlur: () => submitted && setErrors(validateProductForm(form)) });
  const set = <K extends keyof ProductForm>(key: K, value: ProductForm[K]) => setForm((previous) => ({ ...previous, [key]: value }));
  const setMetal = (metal: "gold" | "silver") => setForm((p) => ({ ...p, metal, pricingConfigKey: "", mainCategory: metal === "gold" ? goldRoot?._id || "" : "", subCategory: "", grossWeight: 0, netWeight: 0, moissaniteCaratWeight: 0, moissaniteEntries: [] }));
  const updateImage = (index: number, image?: Image) => setForm((p) => ({ ...p, images: Array.from({ length: 6 }, (_, i) => i === index ? image : p.images[i]).filter((value): value is Image => Boolean(value)) }));
  const uploadImage = async (index: number, file: File) => { try { setUploading(index); const result = await adminApi.uploadImage(file); updateImage(index, { url: result.url, source: "upload" }); } catch { showToast("Image upload failed. Please try again.", "error"); } finally { setUploading(null); } };
  const updateMoissanite = (index: number, patch: Partial<MoissaniteEntry>) => set("moissaniteEntries", form.moissaniteEntries.map((entry, i) => i === index ? { ...entry, ...patch } : entry));
  const addMoissanite = () => set("moissaniteEntries", [...form.moissaniteEntries, { caratWeight: 0 }]);
  const updateDiamond = (index: number, patch: Partial<DiamondEntry>) => set("diamonds", form.diamonds.map((diamond, i) => i === index ? { ...diamond, ...patch } : diamond));
  const saveDiamondOption = async () => { const name = newDiamondCategory.trim(); const subType = newDiamondSubType.trim(); if (!name) return showToast("Enter a diamond category name.", "error"); try { await adminApi.saveDiamondCategory(name, subType); setNewDiamondCategory(""); setNewDiamondSubType(""); await load(); showToast("Diamond category option saved.", "success"); } catch (error) { showToast(error instanceof Error ? error.message : "Diamond category option could not be saved.", "error"); } };
  const addDiamond = () => set("diamonds", [...form.diamonds, { category: "Center", subType: "Round", caratWeight: 0, ratePerCt: 0, colorClarity: "EF/VVSVS" }]);
  const payload = (): Partial<Product> => ({ ...form, metal: form.metal as "gold" | "silver", grossWeight: Number(form.grossWeight), netWeight: form.metal === "gold" ? Number(form.netWeight) : undefined, moissaniteCaratWeight: form.metal === "silver" ? form.moissaniteCaratWeight : undefined, moissaniteEntries: form.metal === "silver" ? form.moissaniteEntries : undefined });
  useEffect(() => { if (!form.metal || !form.pricingConfigKey || !form.mainCategory || !form.subCategory) { setPreview([]); return; } const timer = setTimeout(() => { void adminApi.previewPrice(payload()).then(setPreview).catch(() => setPreview([])); }, 400); return () => clearTimeout(timer); }, [form]);
  const openCreate = () => { setEditing(null); setForm(blank()); setPreview([]); setErrors({}); setSubmitted(false); setCreating(true); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openEdit = (product: Product) => { const metal = product.metal || "gold"; setEditing(product); setForm({ ...blank(), ...product, metal, pricingConfigKey: product.pricingConfigKey || "", mainCategory: categoryId(product.mainCategory), subCategory: categoryId(product.subCategory), images: product.images || [], sizes: STANDARD_RING_SIZES, colors: product.colors || [], grossWeight: typeof product.grossWeight === "number" ? product.grossWeight : 0, netWeight: typeof product.netWeight === "number" ? product.netWeight : 0, moissaniteEntries: product.moissaniteEntries || (product.moissaniteCaratWeight !== undefined ? [{ caratWeight: product.moissaniteCaratWeight }] : []), diamonds: product.diamonds || [] }); setErrors({}); setSubmitted(false); setCreating(true); };
  const save = async (e: FormEvent, publish: boolean) => {
    e.preventDefault();
    if (saving) return;
    setSubmitted(true);
    const fieldErrors = validateProductForm(form);
    setErrors(fieldErrors);
    if (uploading !== null) { showToast("Wait for the image upload to finish before saving.", "info"); return; }
    if (Object.keys(fieldErrors).length) {
      firstInvalidRef.current = document.querySelector<HTMLElement>(`[data-field="${Object.keys(fieldErrors)[0]}"]`);
      showToast(`Please complete ${Object.keys(fieldErrors).length} required field${Object.keys(fieldErrors).length === 1 ? "" : "s"}.`, "error");
      return;
    }
    try {
      setSaving(true);
      const data = { ...payload(), isActive: publish };
      if (editing) await adminApi.updateProduct(editing.id || editing._id || "", data); else await adminApi.createProduct(data);
      showToast(`Product ${editing ? "updated" : "created"} successfully.`, "success");
      setCreating(false); setEditing(null); setForm(blank()); setErrors({}); setSubmitted(false); await load();
    } catch (error) { showToast(error instanceof Error ? error.message : "Product could not be saved.", "error"); }
    finally { setSaving(false); }
  };
  if (!creating) return <div className="admin-products"><header className="admin-page-heading"><div><p>Catalogue management</p><h1>Products</h1><span>Products use category-level pricing configurations.</span></div><button className="admin-primary" onClick={openCreate}>+ Add product</button></header>{Object.keys(errors).length > 0 && <div className="admin-error-summary" role="alert">Please complete {Object.keys(errors).length} required field{Object.keys(errors).length === 1 ? "" : "s"}.</div>}<section className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th /></tr></thead><tbody>{items.map((product) => <tr key={product.id || product._id}><td className="admin-product-cell"><img src={product.images?.[0]?.url} loading="lazy" decoding="async" alt="" /><span><b>{product.title}</b><small>{product.SKU}</small></span></td><td>{categoryName(product.mainCategory)}<small>{categoryName(product.subCategory)}</small></td><td>{currency(product.prices?.[0]?.finalPrice || 0)}</td><td><button className="admin-text-button" onClick={() => openEdit(product)}>Edit</button><button className="admin-text-button danger" onClick={() => { if (window.confirm(`Permanently delete ${product.title || product.SKU}?`)) void adminApi.deleteProduct(product.id || product._id || "").then(() => { setItems((current) => current.filter((item) => (item.id || item._id) !== (product.id || product._id))); showToast("Product deleted permanently.", "success"); }).catch((error) => showToast(error instanceof Error ? error.message : "Product could not be deleted.", "error")); }}>Delete</button></td></tr>)}</tbody></table></section></div>;
  const isMoissanite = form.metal === "silver" && selectedSilverType === "moissanite";
  return <form onSubmit={(e) => void save(e, true)} className="admin-editor"><header className="admin-page-heading"><div><p>Catalogue management</p><h1>{editing ? "Edit product" : "Create product"}</h1><span>Fields are aligned with the Product schema and current pricing engines.</span></div><button type="button" className="admin-secondary" onClick={() => setCreating(false)}>Back to products</button></header>{Object.keys(errors).length > 0 && <div className="admin-error-summary" role="alert">Please complete {Object.keys(errors).length} required field{Object.keys(errors).length === 1 ? "" : "s"}.</div>}
    <section className="admin-section"><div className="admin-section-heading"><span>01</span><div><h2>Identity, configuration & category</h2></div></div><div className="admin-grid"><Field name="title" label="Product title" required error={errors.title}><input {...fieldProps("title")} className="admin-input" value={form.title} onChange={(e) => set("title", e.target.value)} /></Field><Field name="SKU" label="SKU" required error={errors.SKU}><input {...fieldProps("SKU")} className="admin-input" value={form.SKU} onChange={(e) => set("SKU", e.target.value)} /></Field><Field name="metal" label="Metal" required error={errors.metal}><select {...fieldProps("metal")} className="admin-input" value={form.metal} onChange={(e) => setMetal(e.target.value as "gold" | "silver")}><option value="">Select metal</option><option value="gold">Gold</option><option value="silver">Silver</option></select></Field><Field name="pricingConfigKey" label="Pricing configuration" required error={errors.pricingConfigKey}><select {...fieldProps("pricingConfigKey")} className="admin-input" value={form.pricingConfigKey} onChange={(e) => set("pricingConfigKey", e.target.value)}><option value="">Select active pricing configuration</option>{compatibleConfigs.map((config) => <option key={config._id} value={config.key}>{config.key} — {config.categoryType}</option>)}</select></Field>{form.metal === "gold" && <Field name="subCategory" label="Gold sub-category" required error={errors.subCategory}><select {...fieldProps("subCategory")} className="admin-input" value={form.subCategory} onChange={(e) => set("subCategory", e.target.value)}><option value="">Select sub-category</option>{goldLeaves.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></Field>}{form.metal === "silver" && <><Field name="mainCategory" label="Silver type" required error={errors.mainCategory}><select {...fieldProps("mainCategory")} className="admin-input" value={form.mainCategory} onChange={(e) => setForm((p) => ({ ...p, mainCategory: e.target.value, subCategory: "", pricingConfigKey: "" }))}><option value="">Select type</option>{silverTypes.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></Field><Field name="subCategory" label="Silver sub-category" required error={errors.subCategory}><select {...fieldProps("subCategory")} className="admin-input" value={form.subCategory} onChange={(e) => set("subCategory", e.target.value)}><option value="">Select sub-category</option>{silverLeaves.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></Field></>}<Field label="Description"><textarea className="admin-input admin-textarea" value={form.description} onChange={(e) => set("description", e.target.value)} /></Field></div></section>
    <section className="admin-section"><div className="admin-section-heading"><span>02</span><div><h2>Weight & price preview</h2><p>Gold uses one manual gross and net weight; 14kt and 18kt rates are calculated from the universal 24kt rate.</p></div></div>{form.metal === "gold" && <><div className="admin-grid"><Field label="Gross weight (g)" required hint="Used for Gold Value."><input className="admin-input" type="number" min="0" step="0.01" value={form.grossWeight} onChange={(e) => set("grossWeight", number(e.target.value))} /></Field><Field label="Net weight (g)" required hint="Used only for Making Charge."><input className="admin-input" type="number" min="0" step="0.01" value={form.netWeight} onChange={(e) => set("netWeight", number(e.target.value))} /></Field></div><div className="admin-pricing-grid">{(["14kt", "18kt"] as Karat[]).map((karat) => { const price = preview.find((item) => item.karat === karat); return <div className="admin-karat-card" key={karat}><b>{karat} calculated price</b><small>Rate: {currency(price?.goldRate || 0)}/g · Gold value: {currency(price?.goldValue || 0)}</small><strong>{currency(price?.finalPrice || 0)}</strong></div>; })}</div></>}{form.metal === "silver" && <div className="admin-grid"><Field label="Gross weight (g)" required hint="Used separately for Silver Value and Making Charge."><input className="admin-input" type="number" min="0" step="0.01" value={form.grossWeight} onChange={(e) => set("grossWeight", number(e.target.value))} /></Field>{isMoissanite && <div className="admin-field"><span>Moissanite entries</span>{form.moissaniteEntries.map((entry, index) => <div className="flex gap-2" key={index}><input className="admin-input" aria-label={`Moissanite ${index + 1} carat weight`} type="number" min="0" step="0.01" value={entry.caratWeight} onChange={(e) => updateMoissanite(index, { caratWeight: number(e.target.value) })} placeholder="Carat weight" /><button type="button" className="admin-text-button danger" onClick={() => set("moissaniteEntries", form.moissaniteEntries.filter((_, i) => i !== index))}>Remove</button></div>)}<button type="button" className="admin-secondary" onClick={addMoissanite}>+ Add Moissanite</button><small>Colour/clarity is optional and inactive pending confirmation. The universal rate must be set in Admin Settings before pricing.</small></div>}<div className="admin-karat-card"><b>Silver B2C price preview</b><small>Silver Value: {currency(preview[0]?.silverValue || preview[0]?.metalValue || 0)}</small><small>Making Charge: {currency(preview[0]?.makingValue || 0)}</small>{isMoissanite && <><small>Moissanite Value: {currency(preview[0]?.moissaniteValue || 0)}</small><small>Certificate Charge: {currency(preview[0]?.certificateCharges || 0)}</small></>}<small>GST: {currency(preview[0]?.gst || 0)}</small><strong>{currency(preview[0]?.finalPrice || 0)}</strong><small>Silver B2B pricing: pending — currently follows B2C.</small></div></div>}</section>
    {form.metal === "gold" && <section className="admin-section"><div className="admin-section-heading"><span>03</span><div><h2>Diamonds</h2><p>Each entry is saved with the fixed EF/VVSVS color/clarity.</p></div></div>{form.diamonds.map((diamond, index) => <div className="admin-grid" key={index}><Field label="Category"><input className="admin-input" list="diamond-category-options" value={diamond.category} onChange={(e) => updateDiamond(index, { category: e.target.value })} /></Field><Field label="Sub-type"><input className="admin-input" list={`diamond-subtype-options-${index}`} value={diamond.subType} onChange={(e) => updateDiamond(index, { subType: e.target.value })} /><datalist id={`diamond-subtype-options-${index}`}>{diamondCategories.find((option) => option.name === diamond.category)?.subTypes.map((subType) => <option key={subType} value={subType} />)}</datalist></Field><Field label="Carat weight"><input className="admin-input" type="number" min="0" step="0.01" value={diamond.caratWeight} onChange={(e) => updateDiamond(index, { caratWeight: number(e.target.value) })} /></Field><Field label="Rate per ct"><input className="admin-input" type="number" min="0" value={diamond.ratePerCt || 0} onChange={(e) => updateDiamond(index, { ratePerCt: number(e.target.value) })} /></Field><button type="button" className="admin-text-button danger" onClick={() => set("diamonds", form.diamonds.filter((_, i) => i !== index))}>Remove diamond</button></div>)}<datalist id="diamond-category-options">{diamondCategories.map((option) => <option key={option._id} value={option.name} />)}</datalist><div className="admin-grid"><Field label="New diamond category"><input className="admin-input" value={newDiamondCategory} onChange={(event) => setNewDiamondCategory(event.target.value)} placeholder="e.g. Accent" /></Field><Field label="New sub-type"><input className="admin-input" value={newDiamondSubType} onChange={(event) => setNewDiamondSubType(event.target.value)} placeholder="e.g. Oval" /></Field><button type="button" className="admin-secondary" onClick={() => void saveDiamondOption()}>Save diamond option</button></div><button type="button" className="admin-secondary" onClick={addDiamond}>+ Add diamond</button></section>
}
    <section className="admin-section"><div className="admin-section-heading"><span>04</span><div><h2>Media & visibility</h2><p>Use one to six images. Sizes are standardized customer-side from 5 to 25.</p></div></div><>{errors.images && <p className="admin-inline-error" id="images-error" role="alert">{errors.images}</p>}<div className="admin-media-grid" data-field="images" tabIndex={-1} aria-invalid={Boolean(errors.images)} aria-describedby={errors.images ? "images-error" : undefined}>{Array.from({ length: 6 }, (_, index) => <MediaCard key={index} index={index} image={form.images[index]} uploading={uploading === index} onUpload={(file) => void uploadImage(index, file)} onUrl={(url) => updateImage(index, url ? { url, source: "link" } : undefined)} onRemove={() => updateImage(index, undefined)} />)}</div></><Field label="External video URL"><input className="admin-input" type="url" value={form.videoLink} onChange={(e) => set("videoLink", e.target.value)} /></Field><div className="admin-colours"><b>Available metal colours</b><div>{PRODUCT_COLORS.map((color) => <label key={color} className={`admin-colour-option ${form.colors.includes(color) ? "selected" : ""}`}><input type="checkbox" checked={form.colors.includes(color)} onChange={(e) => set("colors", e.target.checked ? [...form.colors, color] : form.colors.filter((item) => item !== color))} />{color}</label>)}</div></div><div className="admin-toggle-grid"><Toggle label="Product visibility" checked={form.isActive} onChange={(value) => set("isActive", value)} /><Toggle label="Best seller" checked={form.isBestSeller} onChange={(value) => set("isBestSeller", value)} /><Toggle label="New arrival" checked={form.isNewProduct} onChange={(value) => set("isNewProduct", value)} /></div></section>
    <footer className="admin-action-bar"><button type="button" className="admin-secondary" onClick={() => setCreating(false)}>Cancel</button><span /><button type="button" className="admin-secondary" disabled={saving || uploading !== null} onClick={(e) => void save(e as unknown as FormEvent, false)}>Save draft</button><button type="submit" className="admin-primary" disabled={saving || uploading !== null}>{saving ? "Savingï¿½" : "Publish product"}</button></footer>
  </form>;
}
