import { ChangeEvent, DragEvent, FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { adminApi, type PricingConfig } from "../api/admin.api";
import type { Category, DiamondEntry, PriceBreakdown, Product } from "../types";
import { PRODUCT_COLORS } from "../constants/product";

type Karat = "14kt" | "18kt";
type Image = { url: string; source: "link" | "upload" };
type ProductForm = {
  SKU: string; title: string; description: string; metal: "" | "gold" | "silver"; pricingConfigKey: string;
  mainCategory: string; subCategory: string; images: Image[]; videoLink: string; sizes: number[]; colors: string[];
  grossWeight: Record<Karat, number> | number; netWeight: Record<Karat, number>; moissaniteCaratWeight: number;
  diamonds: DiamondEntry[]; isBestSeller: boolean; isNewProduct: boolean; isActive: boolean;
};
const blank = (): ProductForm => ({ SKU: "", title: "", description: "", metal: "", pricingConfigKey: "", mainCategory: "", subCategory: "", images: [], videoLink: "", sizes: [], colors: [], grossWeight: { "14kt": 0, "18kt": 0 }, netWeight: { "14kt": 0, "18kt": 0 }, moissaniteCaratWeight: 0, diamonds: [], isBestSeller: false, isNewProduct: false, isActive: true });
const categoryId = (value?: string | { _id: string } | null) => typeof value === "string" ? value : value?._id || "";
const categoryName = (value?: Category | string | null) => !value ? "Uncategorised" : typeof value === "string" ? value : value.name;
const currency = (value: number) => `?${Math.round(value || 0).toLocaleString("en-IN")}`;
const number = (value: string) => value === "" ? 0 : Number(value);

function Field({ label, hint, required, children }: { label: string; hint?: string; required?: boolean; children: React.ReactNode }) { return <label className="admin-field"><span>{label} {required && <em>*</em>}</span>{children}{hint && <small>{hint}</small>}</label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="admin-toggle-card"><span><b>{label}</b></span><input aria-label={label} type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><i /></label>; }
function MediaCard({ index, image, uploading, onUpload, onUrl, onRemove }: { index: number; image?: Image; uploading: boolean; onUpload: (file: File) => void; onUrl: (url: string) => void; onRemove: () => void }) {
  const fileChange = (e: ChangeEvent<HTMLInputElement>) => e.target.files?.[0] && onUpload(e.target.files[0]);
  const drop = (e: DragEvent<HTMLLabelElement>) => { e.preventDefault(); const file = e.dataTransfer.files[0]; if (file) onUpload(file); };
  return <article className="admin-media-card"><div className="admin-media-preview">{image ? <img src={image.url} alt={`Product image ${index + 1}`} /> : <span>Image {index + 1}{index === 0 ? " � Primary" : ""}</span>}</div><div className="admin-media-body"><b>Image {index + 1}{index === 0 ? " (Primary)" : ""}</b><label className="admin-dropzone" onDragOver={(e) => e.preventDefault()} onDrop={drop}><input type="file" accept="image/*" onChange={fileChange} />{uploading ? "Uploading image�" : "Upload or drop an image"}</label><div className="admin-media-or">or paste an external URL</div><input className="admin-input" value={image?.source === "link" ? image.url : ""} onChange={(e) => onUrl(e.target.value)} placeholder="https://�" />{image && <button type="button" className="admin-text-button danger" onClick={onRemove}>Remove</button>}</div></article>;
}

export default function Products() {
  const [items, setItems] = useState<Product[]>([]), [categories, setCategories] = useState<Category[]>([]), [configs, setConfigs] = useState<PricingConfig[]>([]);
  const [form, setForm] = useState<ProductForm>(blank()), [editing, setEditing] = useState<Product | null>(null), [preview, setPreview] = useState<PriceBreakdown[]>([]);
  const [creating, setCreating] = useState(false), [message, setMessage] = useState(""), [saving, setSaving] = useState(false), [uploading, setUploading] = useState<number | null>(null);
  const load = useCallback(async () => { const [products, categoryList, configList] = await Promise.all([adminApi.adminProducts(), adminApi.categories(), adminApi.pricingConfigs()]); setItems(products); setCategories(categoryList); setConfigs(configList); }, []);
  useEffect(() => { void load().catch(() => setMessage("Couldn�t load catalogue data.")); }, [load]);
  const goldRoot = useMemo(() => categories.find((c) => c.metal === "gold" && c.categoryKind === "metal-root"), [categories]);
  const goldLeaves = useMemo(() => categories.filter((c) => c.metal === "gold" && c.categoryKind === "subcategory" && categoryId(c.parent) === goldRoot?._id), [categories, goldRoot]);
  const silverTypes = useMemo(() => categories.filter((c) => c.metal === "silver" && c.categoryKind === "type"), [categories]);
  const silverLeaves = useMemo(() => categories.filter((c) => c.metal === "silver" && c.categoryKind === "subcategory" && categoryId(c.parent) === form.mainCategory), [categories, form.mainCategory]);
  const compatibleConfigs = useMemo(() => configs.filter((c) => !form.metal || c.metal === form.metal), [configs, form.metal]);
  const set = <K extends keyof ProductForm>(key: K, value: ProductForm[K]) => setForm((previous) => ({ ...previous, [key]: value }));
  const setMetal = (metal: "gold" | "silver") => setForm((p) => ({ ...p, metal, pricingConfigKey: "", mainCategory: metal === "gold" ? goldRoot?._id || "" : "", subCategory: "", grossWeight: metal === "gold" ? { "14kt": 0, "18kt": 0 } : 0, netWeight: { "14kt": 0, "18kt": 0 }, moissaniteCaratWeight: 0 }));
  const setWeight = (field: "grossWeight" | "netWeight", karat: Karat, value: number) => setForm((p) => ({ ...p, [field]: { ...(typeof p[field] === "object" ? p[field] : { "14kt": 0, "18kt": 0 }), [karat]: value } as Record<Karat, number> }));
  const updateImage = (index: number, image?: Image) => setForm((p) => ({ ...p, images: Array.from({ length: 6 }, (_, i) => i === index ? image : p.images[i]).filter((value): value is Image => Boolean(value)) }));
  const uploadImage = async (index: number, file: File) => { try { setUploading(index); const result = await adminApi.uploadImage(file); updateImage(index, { url: result.url, source: "upload" }); } catch { setMessage("Image upload failed. Please try again."); } finally { setUploading(null); } };
  const updateDiamond = (index: number, patch: Partial<DiamondEntry>) => set("diamonds", form.diamonds.map((diamond, i) => i === index ? { ...diamond, ...patch } : diamond));
  const addDiamond = () => set("diamonds", [...form.diamonds, { category: "Center", subType: "Round", caratWeight: 0, ratePerCt: 0, colorClarity: "EF/VVSVS" }]);
  const payload = (): Partial<Product> => ({ ...form, metal: form.metal as "gold" | "silver", grossWeight: form.metal === "silver" ? Number(form.grossWeight) : form.grossWeight, netWeight: form.metal === "gold" ? form.netWeight : undefined, moissaniteCaratWeight: form.metal === "silver" ? form.moissaniteCaratWeight : undefined });
  useEffect(() => { if (!form.metal || !form.pricingConfigKey || !form.mainCategory || !form.subCategory) { setPreview([]); return; } const timer = setTimeout(() => { void adminApi.previewPrice(payload()).then(setPreview).catch(() => setPreview([])); }, 400); return () => clearTimeout(timer); }, [form]);
  const openCreate = () => { setEditing(null); setForm(blank()); setPreview([]); setCreating(true); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openEdit = (product: Product) => { const metal = product.metal || "gold"; setEditing(product); setForm({ ...blank(), ...product, metal, pricingConfigKey: product.pricingConfigKey || "", mainCategory: categoryId(product.mainCategory), subCategory: categoryId(product.subCategory), images: product.images || [], sizes: product.sizes || [], colors: product.colors || [], grossWeight: product.grossWeight || (metal === "silver" ? 0 : { "14kt": 0, "18kt": 0 }), netWeight: (product.netWeight as Record<Karat, number>) || { "14kt": 0, "18kt": 0 }, diamonds: product.diamonds || [] }); setCreating(true); };
  const save = async (e: FormEvent, publish: boolean) => { e.preventDefault(); if (!form.SKU.trim() || !form.title.trim() || !form.metal || !form.pricingConfigKey || !form.mainCategory || !form.subCategory || !form.images.length) { setMessage("SKU, title, metal, pricing config, category and at least one image are required."); return; } try { setSaving(true); const data = { ...payload(), isActive: publish }; if (editing) await adminApi.updateProduct(editing.id || editing._id || "", data); else await adminApi.createProduct(data); setMessage(`Product ${editing ? "updated" : "created"} successfully.`); setCreating(false); setEditing(null); setForm(blank()); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Product could not be saved."); } finally { setSaving(false); } };
  if (!creating) return <div className="admin-products"><header className="admin-page-heading"><div><p>Catalogue management</p><h1>Products</h1><span>Products use category-level pricing configurations.</span></div><button className="admin-primary" onClick={openCreate}>+ Add product</button></header>{message && <div role="status" className="admin-notice">{message}</div>}<section className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th /></tr></thead><tbody>{items.map((product) => <tr key={product.id || product._id}><td className="admin-product-cell"><img src={product.images?.[0]?.url} alt="" /><span><b>{product.title}</b><small>{product.SKU}</small></span></td><td>{categoryName(product.mainCategory)}<small>{categoryName(product.subCategory)}</small></td><td>{currency(product.prices?.[0]?.finalPrice || 0)}</td><td><button className="admin-text-button" onClick={() => openEdit(product)}>Edit</button></td></tr>)}</tbody></table></section></div>;
  const isMoissanite = form.metal === "silver" && configs.find((config) => config.key === form.pricingConfigKey)?.categoryType.toLowerCase().includes("moissanite");
  return <form onSubmit={(e) => void save(e, true)} className="admin-editor"><header className="admin-page-heading"><div><p>Catalogue management</p><h1>{editing ? "Edit product" : "Create product"}</h1><span>Fields are aligned with the Product schema and current pricing engines.</span></div><button type="button" className="admin-secondary" onClick={() => setCreating(false)}>Back to products</button></header>{message && <div role="status" className="admin-notice">{message}</div>}
    <section className="admin-section"><div className="admin-section-heading"><span>01</span><div><h2>Identity, configuration & category</h2></div></div><div className="admin-grid"><Field label="Product title" required><input className="admin-input" value={form.title} onChange={(e) => set("title", e.target.value)} /></Field><Field label="SKU" required><input className="admin-input" value={form.SKU} onChange={(e) => set("SKU", e.target.value)} /></Field><Field label="Metal" required><select className="admin-input" value={form.metal} onChange={(e) => setMetal(e.target.value as "gold" | "silver")}><option value="">Select metal</option><option value="gold">Gold</option><option value="silver">Silver</option></select></Field><Field label="Pricing configuration" required><select className="admin-input" value={form.pricingConfigKey} onChange={(e) => set("pricingConfigKey", e.target.value)}><option value="">Select active pricing configuration</option>{compatibleConfigs.map((config) => <option key={config._id} value={config.key}>{config.key} � {config.categoryType}</option>)}</select></Field>{form.metal === "gold" && <Field label="Gold sub-category" required><select className="admin-input" value={form.subCategory} onChange={(e) => set("subCategory", e.target.value)}><option value="">Select sub-category</option>{goldLeaves.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></Field>}{form.metal === "silver" && <><Field label="Silver type" required><select className="admin-input" value={form.mainCategory} onChange={(e) => setForm((p) => ({ ...p, mainCategory: e.target.value, subCategory: "" }))}><option value="">Select type</option>{silverTypes.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></Field><Field label="Silver sub-category" required><select className="admin-input" value={form.subCategory} onChange={(e) => set("subCategory", e.target.value)}><option value="">Select sub-category</option>{silverLeaves.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></Field></>}<Field label="Description"><textarea className="admin-input admin-textarea" value={form.description} onChange={(e) => set("description", e.target.value)} /></Field></div></section>
    <section className="admin-section"><div className="admin-section-heading"><span>02</span><div><h2>Weight & price preview</h2><p>Gold uses separate 14kt/18kt gross and net weights; Silver uses one gross weight.</p></div></div>{form.metal === "gold" && <div className="admin-pricing-grid">{(["14kt", "18kt"] as Karat[]).map((karat) => <div className="admin-karat-card" key={karat}><b>{karat} gold</b><Field label="Gross weight (g)" required><input className="admin-input" type="number" min="0" step="0.01" value={(form.grossWeight as Record<Karat, number>)[karat]} onChange={(e) => setWeight("grossWeight", karat, number(e.target.value))} /></Field><Field label="Net weight (g)" required><input className="admin-input" type="number" min="0" step="0.01" value={form.netWeight[karat]} onChange={(e) => setWeight("netWeight", karat, number(e.target.value))} /></Field><strong>{currency(preview.find((price) => price.karat === karat)?.finalPrice || 0)}</strong></div>)}</div>}{form.metal === "silver" && <div className="admin-grid"><Field label="Gross weight (g)" required><input className="admin-input" type="number" min="0" step="0.01" value={typeof form.grossWeight === "number" ? form.grossWeight : 0} onChange={(e) => set("grossWeight", number(e.target.value))} /></Field>{isMoissanite && <Field label="Moissanite carat weight" required hint="Used by Silver Moissanite pricing."><input className="admin-input" type="number" min="0" step="0.01" value={form.moissaniteCaratWeight} onChange={(e) => set("moissaniteCaratWeight", number(e.target.value))} /></Field>}<strong>{currency(preview[0]?.finalPrice || 0)}</strong></div>}</section>
    <section className="admin-section"><div className="admin-section-heading"><span>03</span><div><h2>Diamonds</h2><p>Each entry is saved with the fixed EF/VVSVS color/clarity.</p></div></div>{form.diamonds.map((diamond, index) => <div className="admin-grid" key={index}><Field label="Category"><select className="admin-input" value={diamond.category} onChange={(e) => updateDiamond(index, { category: e.target.value as DiamondEntry["category"] })}><option>Center</option><option>Small</option></select></Field><Field label="Sub-type"><select className="admin-input" value={diamond.subType} onChange={(e) => updateDiamond(index, { subType: e.target.value as DiamondEntry["subType"] })}><option>Round</option><option>Fancy</option></select></Field><Field label="Carat weight"><input className="admin-input" type="number" min="0" step="0.01" value={diamond.caratWeight} onChange={(e) => updateDiamond(index, { caratWeight: number(e.target.value) })} /></Field><Field label="Rate per ct"><input className="admin-input" type="number" min="0" value={diamond.ratePerCt || 0} onChange={(e) => updateDiamond(index, { ratePerCt: number(e.target.value) })} /></Field><button type="button" className="admin-text-button danger" onClick={() => set("diamonds", form.diamonds.filter((_, i) => i !== index))}>Remove diamond</button></div>)}<button type="button" className="admin-secondary" onClick={addDiamond}>+ Add diamond</button></section>
    <section className="admin-section"><div className="admin-section-heading"><span>04</span><div><h2>Media, sizes & visibility</h2><p>Use one to six images; sizes must be whole numbers from 5 to 25.</p></div></div><div className="admin-media-grid">{Array.from({ length: 6 }, (_, index) => <MediaCard key={index} index={index} image={form.images[index]} uploading={uploading === index} onUpload={(file) => void uploadImage(index, file)} onUrl={(url) => updateImage(index, url ? { url, source: "link" } : undefined)} onRemove={() => updateImage(index, undefined)} />)}</div><Field label="External video URL"><input className="admin-input" type="url" value={form.videoLink} onChange={(e) => set("videoLink", e.target.value)} /></Field><div className="admin-colours"><b>Available sizes</b><div>{Array.from({ length: 21 }, (_, i) => i + 5).map((size) => <label key={size} className={`admin-colour-option ${form.sizes.includes(size) ? "selected" : ""}`}><input type="checkbox" checked={form.sizes.includes(size)} onChange={(e) => set("sizes", e.target.checked ? [...form.sizes, size] : form.sizes.filter((item) => item !== size))} />{size}</label>)}</div><b>Available metal colours</b><div>{PRODUCT_COLORS.map((color) => <label key={color} className={`admin-colour-option ${form.colors.includes(color) ? "selected" : ""}`}><input type="checkbox" checked={form.colors.includes(color)} onChange={(e) => set("colors", e.target.checked ? [...form.colors, color] : form.colors.filter((item) => item !== color))} />{color}</label>)}</div></div><div className="admin-toggle-grid"><Toggle label="Product visibility" checked={form.isActive} onChange={(value) => set("isActive", value)} /><Toggle label="Best seller" checked={form.isBestSeller} onChange={(value) => set("isBestSeller", value)} /><Toggle label="New arrival" checked={form.isNewProduct} onChange={(value) => set("isNewProduct", value)} /></div></section>
    <footer className="admin-action-bar"><button type="button" className="admin-secondary" onClick={() => setCreating(false)}>Cancel</button><span /><button type="button" className="admin-secondary" disabled={saving} onClick={(e) => void save(e as unknown as FormEvent, false)}>Save draft</button><button type="submit" className="admin-primary" disabled={saving}>{saving ? "Saving�" : "Publish product"}</button></footer>
  </form>;
}